name: Claim Exploration Rewards

node: exploration

trigger: "exploration.state.isClaimActive == true"

ttl: 2h

steps:
  - click: exploration.state.isClaimActive       # Click the claim button on the exploration screen.
    log: "💰 Claiming exploration rewards"
  - click: exploration_claim_confirmation_button
  - click: tap_anywhere_to_exit