name: Train Marksman

node: marksman

priority: 10

trigger: troops.marksman.state.isAvailable

ttl: 2h

steps:
  - if:
      trigger: troops.marksman.state.textStatus == "completed"
      then:
        - click: troops_get_button
        - wait: 500ms

  - if:
      trigger: troops.marksman.state.textStatus == "idle"
      then:
        - click: troops_get_button
        - wait: 500ms
        - click: troops_train_start_button
