name: Exploration Battle

node: exploration_battle

ttl: 0

trigger: "exploration.state.myPower >= exploration.state.enemyPower"

steps:
#  - click: quick_deploy_button
  - wait: 200ms
  - click: exploration_fight_button
  - wait: 10s
  - action: loop
    trigger: '!(exploration.state.battleStatus.contains("Defeat") || exploration.state.battleStatus.contains("Victory"))'
    steps:
      - action: screenshot
        analyze:
          - name: exploration.state.battleStatus
            action: text
            type: string
            threshold: 0.5
      - if:
          trigger: 'exploration.state.battleStatus.contains("defeat")'   # Если результат содержит "defeat" (поражение)
          then:
#            - setTTL: 24h                       # Установка TTL на 24 часа.
#              usecaseName: Exploration Battle   # Название usecase.
            - action: loop_stop
      - if:
          trigger: 'exploration.state.battleStatus.contains("viktory")'  # Если результат содержит "viktor" (победа)
          then:
            - click: battle_continue # Продолжение боя.
      - wait: 5s
  - action: reset
    set: exploration.state.battleStatus
    to: ""
