name: Exploration Battle

node: exploration

trigger: "state.isExplorationAvailable == true"

ttl: 30m

steps:
  - click: explore_button          # Нажатие кнопки "Исследовать".
  - click: quick_deploy_button     # Нажатие кнопки "Быстрый деплой".
  - click: fight_button           # Инициация боя.
  - wait: 5000                    # Ожидание 5000 миллисекунд для получения результата боя.
  - if:
      trigger: "contains(text, 'defeat')"   # Если результат содержит "defeat" (поражение)
      then:
        - setTTL: 24h                   # Установка TTL на 24 часа.
          usecaseName: Exploration Battle  # Название usecase.
        - click: exploration_back           # Возврат в главное меню.
      else:
        - if:
            trigger: "contains(text, 'viktor')"  # Если результат содержит "viktor" (победа)
            then:
              - click: fight_button           # Продолжение боя.
            else:
              - wait: 5000                    # Если результат не распознан, ожидаем повторно.

final_node: main_menu
