name: "🪖 Train Soldiers"

node: barracks

ttl: 1h

trigger: "barracks.state.canTrain == true"

steps:
  - click: barracks_button
  - wait: 500ms

  - click: train_button
  - wait: 300ms

  - click: train_confirm_button
  - set: barracks.state.canTrain
    to: false
