name: Claim Tundra Drill Rewards

node: tundra_adventurer_drill

priority: 16
ttl: 4h

trigger: events.tundraAdventure.state.isAdventurerDrillClaim

steps:
  - action: loop
    trigger: events.tundraAdventure.state.isAdventurerDrillClaim
    steps:
      - click: events.tundraAdventure.state.isAdventurerDrillClaim
      - wait: 200ms
      - action: screenshot
        analyze:
          - name: events.tundraAdventure.state.isAdventurerDrillClaim
            action: findIcon
            threshold: 0.7
            saveAsRegion: true
