name: Train Lancer

node: lancer_city_view

priority: 10

trigger: troops.lancer.state.isAvailable

steps:
  - if:
      trigger: compareText(troops.lancer.state.TextStatus, "Completed")
      then:
        - click: troops_get_button
        - wait: 1s
        - action: reset
          set: troops.lancer.state.TextStatus
          to: "Idle"
        - pushUsecase:
            - trigger: true # Always trigger
              list:
                - name: Train Infantry

  - if:
      trigger: compareText(troops.lancer.state.TextStatus, "Idle")
      then:
        - click: troops_get_button
        - wait: 400ms
        - click: troops.train
        - wait: 500ms
        - click: troops_train_start_button
        - wait: 500ms
          # TODO: check `replenish all`
          # TODO: click - confirm
          # TODO: click (again) - troops_train_start_button
        - click: from_troops_to_main_city
        - wait: 500ms
        - action: reset
          set: troops.lancer.state.TextStatus
          to: "InProgress"
