name: Exploration Battle

node: exploration_battle

ttl: 12h

trigger: "exploration.state.myPower >= exploration.state.enemyPower"

steps:
  - click: quick_deploy_button
  - wait: 200ms
  - click: exploration_fight_button
  - wait: 10s

  - action: loop
    # Цикл продолжается, пока lowerAscii(battleStatus) не содержит ни "defeat", ни "victory"
    trigger: '!(exploration.state.battleStatus.lowerAscii().contains("defeat") || exploration.state.battleStatus.lowerAscii().contains("victory"))'
    steps:
      - action: screenshot
        analyze:
          - name: exploration.state.battleStatus
            action: text
            type: string
            threshold: 0.5
            options:
              clane: true

      - if:
          trigger: 'exploration.state.battleStatus.lowerAscii().contains("defeat")'
          then:
            - action: exploration_battle_back_area
            - action: loop_stop

      - if:
          trigger: 'exploration.state.battleStatus.lowerAscii().contains("victory")'
          then:
            - click: exploration_battle_continue_button
            - wait: 100ms
            - click: exploration_fight_button
            - action: reset
              set: exploration.state.battleStatus
              to: ""

      - wait: 1s

  - action: reset
    set: exploration.state.battleStatus
    to: ""
