name: "⚙️ Detect Bear Hunt and Disable Auto Rally"

node: alliance_war

ttl: 30m

# Событие активно, если иконка Bear Hunt найдена в разделе альянс-война
trigger: "alliance_war.state.isBearHuntEvent == true"

steps:
  - action: screenshot
    analyze:
      - name: alliance_war.state.isBearHuntEvent
        action: exist
        threshold: 0.85
        region: bear_hunt_icon    # Регион с иконкой события, желательно отметить через `saveAsRegion`

  - if:
      trigger: "alliance_war.state.isBearHuntEvent == true"
      then:
        - click: auto_rally_settings_button
        - wait: 200ms
        - click: auto_rally_toggle_off      # Если включено, отключаем
        - wait: 300ms
        - click: auto_rally_close_button
