name: "🕵️ Warn Bad Troop Composition"

node: rally_screen

ttl: 5m

trigger: "rally.state.badTroopRatio >= 0.3"

steps:
  - action: send_message
    to: rally.state.player
    message: "❗ У вас слишком много лучников или осадных войск. Подкорректируйте состав."
