name: R2 Approve (If Active More Than 1 Week)
node: alliance_manage
trigger: "alliance.members.count < alliance.members.max"
steps:
  - click: alliance_member_button
  - wait: 300ms
  - click: alliance_vote
  - wait: 500ms
  - action: screenshot
    analyze:
      - name: alliance_vote
        action: exist
        threshold: 0.9
  - click: alliance_back
